### ISSUE TITLE
can not access admin-ui url after registering successfully

### ISSUE THREAD

**Issue by ngtuna** [cloudfoundry-community/admin-ui-boshrelease#11]
Hi,

I followed the guide and could successfully register admin-ui to CF. However I could not access url when locating on browser, it said: "404 Not Found: Requested route ('admin-ui.mycitus.com') does not exist."

"bosh vms" show all jobs are running. And I could reach nats & postgresql from admin-ui vm.

However, I found this issue on admin-ui.log:
D, [2014-12-08T06:25:23.059197 #1533] DEBUG -- : [ -- ] : [ -- ] : [300 second interval] Starting CC routes discovery...
D, [2014-12-08T06:25:23.060536 #1533] DEBUG -- : [ -- ] : [ -- ] : Error during discovery of routes: #<Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/postgresql>
D, [2014-12-08T06:25:23.060618 #1533] DEBUG -- : [ -- ] : [ -- ] : [300 second interval] Starting CC organizations discovery...
D, [2014-12-08T06:25:23.061578 #1533] DEBUG -- : [ -- ] : [ -- ] : Error during discovery of organizations: #<Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/postgresql>
D, [2014-12-08T06:25:23.061642 #1533] DEBUG -- : [ -- ] : [ -- ] : /var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.14.0/lib/sequel/database/connecting.rb:97:in `require'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.14.0/lib/sequel/database/connecting.rb:97:in `load_adapter'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.14.0/lib/sequel/database/connecting.rb:26:in `adapter_class'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.14.0/lib/sequel/database/connecting.rb:46:in `connect'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/vendor/bundle/ruby/1.9.1/gems/sequel-4.14.0/lib/sequel/core.rb:95:in `connect'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/lib/admin/cc.rb:402:in `select'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/lib/admin/cc.rb:346:in `discover'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/lib/admin/cc.rb:370:in `block in schedule'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/lib/admin/scheduled_thread_pool.rb:23:in `call'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/lib/admin/scheduled_thread_pool.rb:23:in `block (3 levels) in initialize'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/lib/admin/scheduled_thread_pool.rb:13:in `loop'
/var/vcap/data/packages/admin_ui/d8d5adcd22b78b9ec17637414e48b372a910420a.1-1489a94d1f224300c4d328da7baddaf9247e1fa9/admin_ui/lib/admin/scheduled_thread_pool.rb:13:in `block (2 levels) in initialize'

Any idea?

**Comment by sklevenz** [comment]
The route should be *admin.mycitus.com*. Can you please try again?

**Comment by sklevenz** [comment]
closing
