### ISSUE TITLE
Cloud Foundry V211 & Application tab empty

### ISSUE THREAD

**Issue by fbonelle** [cloudfoundry-community/admin-ui-boshrelease#19]
Hi,

Since we updated Cloud Foundry to version V211, application tab in admin-ui is empty (This page requires data from services that are currently unavailable).

The logs I extracted:
D, [2015-06-09T10:42:27.255222 #1368] DEBUG -- : [ -- ] : [ -- ] : Error within AdminUI::ApplicationsViewModel: #<NoMethodError: undefined method `length' for nil:NilClass>
D, [2015-06-09T10:42:27.255390 #1368] DEBUG -- : [ -- ] : [ -- ] : /var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/applications_view_model.rb:205:in `block (3 levels) in do_items'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/applications_view_model.rb:107:in `each_value'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/applications_view_model.rb:107:in `block (2 levels) in do_items'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/applications_view_model.rb:106:in `each_value'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/applications_view_model.rb:106:in `block in do_items'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/applications_view_model.rb:102:in `each'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/applications_view_model.rb:102:in `do_items'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models/base.rb:8:in `items'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models.rb:366:in `discover_applications'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models.rb:328:in `discover'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/view_models.rb:317:in `block in schedule'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/scheduled_thread_pool.rb:23:in `call'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/scheduled_thread_pool.rb:23:in `block (3 levels) in initialize'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/scheduled_thread_pool.rb:13:in `loop'
/var/vcap/data/packages/admin_ui/f2cf62d93b6c3e2a056852414b214ff2aa7d8b17.1-b149d56d08958856a1aa5c2f336612092dccef40/admin_ui/lib/admin/scheduled_thread_pool.rb:13:in `block (2 levels) in initialize'
D, [2015-06-09T10:42:27.255443 #1368] DEBUG -- : [ -- ] : [ -- ] : Caching view model applications data.  Compilation time: 0.003847214 seconds

Regards

related source code https://github.com/cloudfoundry-incubator/admin-ui/blob/2f8eae1ca9371921e7fb8dbd9664d4017ca380d8/lib/admin/view_models/applications_view_model.rb complaining about empty services

**Comment by francoisyanick** [comment]
We have the same issue, nothing in the APPS tab (but an error saying "This page requires data from services that are currently unavailable"). We are using the release v5 for this bosh deployment and CF v214.

We are seeing the same kind of errors than fbonelle in the admin_ui.log ("Error within AdminUI::ApplicationsViewModel...").

**Comment by francoisyanick** [comment]
My issue has been totally fixed with admin-ui-6. Yeah!

**Comment by rkoster** [comment]
@francoisyanick I'm glad to heard that
