### ISSUE TITLE
Can the v6 be accessible as the v5 from s3?

### ISSUE THREAD

**Issue by francoisyanick** [cloudfoundry-community/admin-ui-boshrelease#23]
Hi,

I wonder if there is any plan to update the process to be able to upload the v6 to bosh as it was possible for v5 (e.g.: $ bosh upload release https://admin-ui-boshrelease.s3.amazonaws.com/boshrelease-admin-ui-6.tgz) and also to include the releases/admin-ui-6.yml in the master project?

Thank you

**Comment by sklevenz** [comment]
+1 I am also interested in getting this release uploaded to S3.

**Comment by rkoster** [comment]
For some reason I had the final release local, but not yet pushed to master. The final release can be downloaded from [bosh.io](http://bosh.io/releases/github.com/cloudfoundry-community/admin-ui-boshrelease). I will update the README accordingly.

**Comment by sklevenz** [comment]
Is there any option to get it uploaded to S3? We are using Bosh workspaces which make use of the 

https://github.com/cloudfoundry-community/admin-ui-boshrelease/blob/master/config/final.yml

file.

**Comment by rkoster** [comment]
Bosh-workspace should be able to deal with it just fine, under the hood it is just doing a 'bosh upload release' which downloads the parts from S3 and creates an release tarball locally. Recent version of bosh-workspace also support sepecifying a url for a release for where to download the [release tarball from](https://github.com/cloudfoundry-incubator/bosh-workspace/blob/master/spec/release_spec.rb#L66-L73) the PR which added it can be found [here](https://github.com/cloudfoundry-incubator/bosh-workspace/pull/62)

**Comment by rkoster** [comment]
README was updated here https://github.com/cloudfoundry-community/admin-ui-boshrelease/commit/99a835e16a9d531c683c62378367da471eadb31d

**Comment by francoisyanick** [comment]
Thank you Ruben!
