### ISSUE TITLE
admin-ui v6 not working

### ISSUE THREAD

**Issue by sacgarg** [cloudfoundry-community/admin-ui-boshrelease#27]
I have CF v 214 and admin-ui v6 installed.

I ran the bosh errand to register with uaa, but when i try to login to admin ui I get the below error:

"Insufficient scope for user "

What am i missing?

any help is appreciated.

**Comment by sklevenz** [comment]
Try out this:
http://stackoverflow.com/questions/25113473/how-to-set-sope-for-cloudfoundry-admin-ui

Current v7 release is testet with CF v228. Let me know if you still have problems with newer releases.

**Comment by sklevenz** [comment]
closing
