### ISSUE TITLE
nats.address VS nats.machines in CF 228

### ISSUE THREAD

**Issue by francoisyanick** [cloudfoundry-community/admin-ui-boshrelease#31]
Good day,

I believe there is an issue to create while in CF 228 release, the property nats "address" is mentioned as "machines" instead. If I add the address, the admin-ui deployment is going without any issues. But if I am not adding the "address", then it is complaining. I also tried to convert the admin-ui deployment to respond to "machines" for that property but at the end, it never let me do the deployment successfully.

From the final CF manifest:

{code}
[..]
  nats:
    debug: false
    machines:
    - 10.244.0.6
    address: 10.244.0.6
[..]
{code}

Thx

**Comment by sklevenz** [comment]
See my pull request: https://github.com/cloudfoundry-community/admin-ui-boshrelease/pull/32

**Comment by sklevenz** [comment]
fixed with v7
