### ISSUE TITLE
missing line in admin_ui.yml.erb 

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-community/admin-ui-boshrelease#33]
I found following line missing in admin_ui.yml.erb.

log_file_sftp_keys: [ ]
log_files: [/var/vcap/sys/log/cloud_controller_ng/*.log, admin_ui.log]
doppler_data_file: data/doppler_data.json
doppler_reconnect_delay: 300
doppler_rollup_interval: 30

I use admin ui by doing following steps
    git clone https://github.com/cloudfoundry-community/admin-ui-boshrelease.git
    cd admin-ui-boshrelease    
    git checkout v7
    git submodule init
    git submodule update
Then create bosh release for this and deploy it. I found admin_ui.yml generated from admin_ui.yml.erb doesn't contain those line.

Please tell me the reason for this.
Normally I manually add those line in admin_ui.yml.erb and create bosh release.
bosh create release --force

**Comment by sklevenz** [comment]
Is this configuration required for diego? If you want you can provide a pull request and then it come available with the next release.

**Comment by chrisrana** [comment]
In my case its warden
