### ISSUE TITLE
bosh release is failing 

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-community/admin-ui-boshrelease#34]
I have followed the steps given in the page
bosh create release --force --final --with-tarball
i am getting this error
libyaml/yaml-0.1.4.tgz downloading 460.7K (0%)
/var/lib/gems/1.9.1/gems/blobstore_client-1.3181.0/lib/blobstore_client/local_client.rb:36:in `rescue in get_file': Blobstore object '720a650d-0b1c-4918-92de-7be57b679fe7' not found (Bosh::Blobstore::NotFound)
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3181.0/lib/blobstore_client/local_client.rb:28:in `get_file'

**Comment by sklevenz** [comment]
Without credentials you can't create a final release. For testing you can create a dev release. Just remove --final.

**Comment by chrisrana** [comment]
I want to create final release.I need to account to generate it. Please help me get that credential.

**Comment by sklevenz** [comment]
I recommend to provide a pull request.If accepted then your changes will become part of the next release.
