### ISSUE TITLE
Support for multiple nats addresses

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry-community/admin-ui-boshrelease#35]
Change nats.address property to  nats.machines that takes a list of ips.

**Comment by sklevenz** [comment]
That's already done in v7.

https://github.com/cloudfoundry-community/admin-ui-boshrelease/commit/683a34f26a366f5bf1559f44f442f47b876541f8

**Comment by yatzek** [comment]
In yml template - yes, look at the spec file for admin_ui job:

properties:
 ...
  nats.address:
    description: "IP address of Cloud Foundry NATS server"

**Comment by sklevenz** [comment]
Ah... I am going to fix this. Thanks.

**Comment by sklevenz** [comment]
fixed in #37
