### ISSUE TITLE
monit restart in race conditon

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry-community/admin-ui-boshrelease#38]
Monit is confgured to restart admin_ui after a memory limit is hit. Since the limit has increased to 1G the stop need more time to kill the app. Due to the asynchronous behavior of monit the start script runs while stop is not finished and lead to an admin instance which is no longer under control of monit while monit tries to restart the app and fails because of blocked port.

--> fix restart behavior of monit
--> make limit configurable

**Comment by francoisyanick** [comment]
+1 for the "make limit configurable" as it is also an issue for our organization when things got very busy on our large deployment of CF.
